title: Currents is the Best Album
author: Sam Wheeler
email: sam.wheeler@theinternet.com
description: > # this means to ignore newlines until "baseurl:"
  It's just an awful website.

# social links
twitter_username: twitter is evil
github_username:  sam-wheeler

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
